FROM ubuntu:24.04 AS development

WORKDIR /usr/ocr/src

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    # python3-distutils \ 
    # deprecated in python 3.12+
    python3-venv \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    wget \
    curl \
    git \
    build-essential \
    cmake \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Create symbolic link for python and pip
RUN ln -s /usr/bin/python3 /usr/bin/python

# Copy requirements to install dependencies
COPY requirements.txt .

# Create a virtual environment and install everything in one RUN to maintain activation
# make sure to install paddlepaddle-gpu here because it gets installation from an index-url (-i)
# if we let it install from requirements.txt, it will look for the version in offical site (which does not exist)
RUN python -m venv /env
ENV PATH="/env/bin:$PATH"

RUN pip install --upgrade pip && \
    python -m pip install paddlepaddle==3.0.0 -i https://www.paddlepaddle.org.cn/packages/stable/cpu/ && \
    pip install -r requirements.txt

# Copy code
COPY . .

# Run application
CMD ["python3", "api.py"]


